name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
            pwd
            ls -la
            cd ..
            pwd
            ls -la -R
            echo "Running pylint..."
            pylint ../main.py
    - name: Analysing the code with coverage
      run: |
          echo "Generating coverage report..."
          coverage run -m pytest
          coverage report -m
          coverage xml
      
